user:
  additional_conditions: []
  selectors: []
  records_per_page: 10
  query: verified
  filter_by: ["lastName"]
  filter_alias: "search"
  sort_columns:
    - firstName
    - registerDate
    - userID
