get: # Http Get ===========================================
  "/":
    controller: home
    method: index
  home:
    controller: home
    method: index
  clothes:
    controller: home
    method: vetements
  shop:
    controller: home
    method: boutique_vetements
  account:
    controller: user_account
    method: my_account_show
  error:
    controller: errors
    method: index
  card:
    controller: learning
    method: index
  todo:
    controller: home
    method: todo
  checkout:
    controller: home
    method: index
  lib:
    controller: home
    method: lib
  learn:
    controller: learning
    method: index
  cart:
    controller: shopping_cart
    method: index
  proceed_to_checkout:
    controller: checkout
    method: index
  /{controller}/{method}:
  /{controller}/{method}/{id:[\da-f]+}:
  /admin/{controller}/{method}:
  /admin/{controller}/{method}/{id:[\da-f]+}:
  /client/{controller}/{method}:
  /client/{controller}/{method}/{id:[\da-f]+}:
  #Admin Route
  admin:
    controller: admin_pages
    method: index
post: # Http Post method =========================================================
  visitors:
    controller: visitors
    method: track
  ajaxLogin:
    controller: login_user_with_ajax
    method: index
  ajaxlogout:
    controller: logout_user_with_ajax
    method: index
  ajaxRegister:
    controller: register_user_with_ajax
    method: index
  forgotPassword:
    controller: forgot_password_ajax
    method: index
  verify:
    controller: user_account
    method: verify
  remember_me:
    controller: login_user_with_ajax
    method: rememberMeCheck
  comments:
    controller: comments
    method: newComment
  get_countries:
    controller: country
    method: getCountries
  add_item_into_cart:
    controller: user_cart
    method: add
  proceed_to_checkout:
    controller: checkout
    method: index
  cart:
    controller: shopping_cart
    method: index
  activation/activate/{token:[\da-f]+}:
    controller: activate_user_with_ajax
    method: activate
  error:
    controller: errors
    method: index
  /{controller}/{method}/{id:[\da-f]+}:
  /{controller}/{method}:
  client/{controller}/{method}:
